app:
  jwtSecretKey:
  exchange-rate:
    url:
    secret-key:

spring:
  datasource:
    url:
    username:
    password:
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/master.yml
